name: Default Workflow

on: push

jobs:
  analyse-repos-szz:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Docker Python package
        run: |
          python -m pip install --upgrade pip
          pip install docker
      - name: Run Docker SZZ pipeline
        run: |
          docker pull --all-tags docker.io/cpintodev/szz_github
          python -u driver/setup_analysis.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts
          path: sortie/
  analyse-repos-pharo-python:
    needs: analyse-repos-szz
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Download Python artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-artifacts
          path: sortie/
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Install NPM dependencies
        run: npm install
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Pharo image
        uses: hpi-swa/setup-smalltalkCI@1.3.4
        with:
          smalltalk-image: Moose64-10
      - name: Run code analysis
        run: python -u driver/execute_analysis.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
